var str= "this is \n new line notation";
console.log(str);
var str= "this is \t tab notation";
console.log(str);
var str= "this is \0  notation";
console.log(str);
var str= "this is \\ notation";
console.log(str);
var str= "this is \' notation";
console.log(str);
var str= "this is \" notation";
console.log(str);
var str= "this is \` notation";
console.log(str);
var str= "this is \b notation";
console.log(str);
var str= "this is \f notation";
console.log(str);
